spring:
  #datasource is set by using the spring default env placeholders
  #datasource:
  #  url: ${SPRING_DATASOURCE_URL}
  #  username: ${SPRING_DATASOURCE_USERNAME}
  #  password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  messages:
    basename: vaadin-i18n/translations
  main:
    banner-mode: "off"
  server:
    # tell spring to use https, resolved by nginx beforehand
    forward-headers-strategy: framework
vaadin:
  launch-browser: false
  productionMode: true
bgmo:
  adapter:
    bot:
      telegram:
        enabled: true
        bot-token: "${TELEGRAM_BOT_TOKEN:}"
        bot-username: "${TELEGRAM_BOT_USERNAME:}"
        bot-display-name: "${TELEGRAM_BOT_DISPLAYNAME:}"
        group-chat-id: "${TELEGRAM_BOT_GRP_CHAT_ID:}"
        group-locale: DE
    bgg:
      enabled: true
      apiToken: "${BGG_API_TOKEN:}"
      bggBaseUrl: "https://boardgamegeek.com/xmlapi2"
  core.services:
    base-url: "${APP_BASE_URL:}"
    automation-autostart: false
    security-pw-pepper: "${APP_PASSWORD_PEPPER:}"
    profanityFilterListPath: "${APP_PROFANITY_BLOCK_LIST:}"
