spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bgmo_db
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  messages:
    basename: vaadin-i18n/translations
  profiles:
    active: local # Use gitignored other application-local.yaml
vaadin:
  launch-browser: true
bgmo:
  adapter:
    bot:
      telegram:
        enabled: true
        bot-token: "${TELEGRAM_BOT_TOKEN:}"
        bot-username: "${TELEGRAM_BOT_USERNAME:}"
        group-chat-id: "${TELEGRAM_BOT_GRP_CHAT_ID:}"
        group-locale: DE
  core.services:
    base-url: "http://some-domain.org/"
    automation-autostart: false
    security-pw-pepper: "${APP_PASSWORD_PEPPER:}"
